added github actions

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -1,38 +1,55 @@
-name: docker test
+name: CI Pipeline
 
 on:
-    push:
-      branches:
-        - main
+  push:
+    branches: [main]
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
+  build_and_test:
+    runs-on: ubuntu-latest
+      
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        
+      - name: Run Local Test
+        run: |
+          # Run Docker Compose locally
+          docker-compose up -d
 
-        env:  # Set the environment variable with your MongoDB Atlas URI
-            ATLAS_CONNECTION_STRING: ${{ secrets.ATLAS_CONNECTION_STRING }}
+          # Wait for a moment to let containers start
+          sleep 10
 
-        steps:
-        - name: Checkout repository
-          uses: actions/checkout@v2
-  
-        - name: Set up Docker
-          uses: docker/setup-docker@v2
-          with:
-            docker-host: tcp://localhost:2375  # Connect to the Docker daemon
-  
-        - name: Log in to Docker Hub
-          run: |
-           echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-  
-        - name: Build Docker images
-          run: |
-           docker-compose build
-  
-        - name: Run tests with Docker Compose
-          run: |
-           docker-compose up -d  # Start services in detached mode
-           sleep 10  # Allow some time for services to start
-           docker-compose run app sh -c "python -m unittest discover tests"
+          # Test if the app is running by making a request to localhost:5000
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
+
+          # Exit if response code is not 200
+          if [ $response_code -ne 200 ]; then
+            echo "Local test failed with response code: $response_code"
+            exit 1
+          fi
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2.2.0
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+      
+      - name: Build and Push Flask App Image
+        uses: docker/build-push-action@v2
+        with:
+            context: ./server
+            dockerfile: ./server/Dockerfile
+            push: true
+            tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/todo-flaskapp:${{ github.sha }}
+            
+      - name: Build and Push MongoDB Image
+        uses: docker/build-push-action@v2
+        with:
+            context: ./db
+            dockerfile: ./server/Dockerfile
+            push: true
+            tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/alpine-mongo:${{ github.sha }}
+
 
         
