ci-pipeline

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -1,51 +1,51 @@
-name: ci
 
-on:
-  workflow_dispatch:
-  push:
-    branches:
-      - "main"
+'''name: ci
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  on:
+    workflow_dispatch:
+    push:
+      branches:
+        - "main"
 
-      - name: Run Local Test
-        run: |
-          # Run Docker Compose locally
-          docker-compose up -d
+  jobs:
+    build:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v3
 
-          # Wait for a moment to let containers start
-          sleep 20
+        - name: Run Local Test
+          run: |
+            # Run Docker Compose locally
+            docker-compose up -d
 
-          # Test if the app is running by making a request to 127.0.0.1:5000
-          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000)
+            # Wait for a moment to let containers start
+            sleep 20
 
-          # Exit if response code is not 200
-          if [ $response_code -ne 200 ]; then
-            echo "Local test failed with response code: $response_code"
-            exit 1
-          fi
+            # Test if the app is running by making a request to 127.0.0.1:5000
+            response_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000)
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+            # Exit if response code is not 200
+            if [ $response_code -ne 200 ]; then
+              echo "Local test failed with response code: $response_code"
+              exit 1
+            fi
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        - name: Login to Docker Hub
+          uses: docker/login-action@v2
+          with:
+            username: ${{ secrets.DOCKERHUB_USERNAME }}
+            password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Build and push app
-        uses: docker/build-push-action@v4
-        with:
-          context: ./server
-          file: ./server/Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
+        - name: Set up Docker Buildx
+          uses: docker/setup-buildx-action@v2
 
+        - name: Build and push app
+          uses: docker/build-push-action@v4
+          with:
+            context: ./server
+            file: ./server/Dockerfile
+            push: true
+            tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest'''
 
-        
+          
