added github actions things

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -1,19 +1,34 @@
 name: ci
 
 on:
+  workflow_dispatch:
   push:
     branches:
-      - 'main'
+      - "main"
 
 jobs:
-  docker:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+      - name: Checkout
+        uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Run Local Test
+        run: |
+          # Run Docker Compose locally
+          docker-compose up -d
+
+          # Wait for a moment to let containers start
+          sleep 20
+
+          # Test if the app is running by making a request to 127.0.0.1:5000
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000)
+
+          # Exit if response code is not 200
+          if [ $response_code -ne 200 ]; then
+            echo "Local test failed with response code: $response_code"
+            exit 1
+          fi
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -21,11 +36,16 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Build and push
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build and push app
         uses: docker/build-push-action@v4
         with:
+          context: ./server
+          file: ./server/Dockerfile
           push: true
-          tags: user/app:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
 
 
         
